name: moodleci

on: 
    push:
        branches:
            - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
    - uses: actions/checkout@v3
    - name: Checkout repo
    - uses: easingthemes/ssh-deploy@main


      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "/var/lib/docker/volumes/root_moodle_data/_data/theme/adaptable/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}