name: Moodle

on:
  push:
    branches:
      - main
     
      jobs:
        build:
          runs-on: ubuntu-latest
      
          steps:
            - name: Checkout repo
              uses: actions/checkout@v3
      
            - name: Install rsync
              run: sudo apt-get update && sudo apt-get install -y rsync
      
            - name: Deploy via SSH
              run: rsync -rlgoDzvc -i --delete /var/lib/docker/volumes/root_moodle_data/_data/theme/adaptable/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}
      
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
      