name: moodleci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H -t rsa ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}

      - name: Deploy via SSH
        run: rsync -rlgoDzvc -i --delete /var/lib/docker/volumes/root_moodle_data/_data/theme/adaptable/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
